PUT http://localhost:8000/api/updateUsernameInAcitivityData
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
 "username":"shopmissbehavin1",
    "UpdatedUsername":"shopmissbehavin"
}