POST http://localhost:8000/api/addPlacement
Content-Type: application/json
Authorization: Bearer YOUR_ACCESS_TOKEN

{
    "placement": "202-E3",
    "username": "praycloths.store",
    "password": "123456",
    "twoFactorCode": ""
}

